name: change_background

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # Sử dụng action "checkout" để sao copy code từ repository vào máy ảo Ubuntu
      uses: actions/checkout@v2
    - name: Update README.md
      run: |
        date
        chmod +x change-background.sh && ./change-background.sh
        git config --global user.email "cqvnno1@gmail.com"
        git config --global user.name "quoc9x"
        git add .
        git commit -m "Change background" || echo "No changes to commit"
        git push
