name: change_background

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # Sử dụng action "checkout" để sao copy code từ repository vào máy ảo Ubuntu
      uses: actions/checkout@v2
    - name: Update README.md
      run: |
        git config --global user.email "cqvnno1@gmail.com"
        git config --global user.name "quoc9x"
        touch test
        echo 123 > test
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push
